name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm db:check || true # drizzle check (no DB yet)
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test -- --ci
      - run: pnpm test:ui || true # optional in CI; keep E2E light until backend is ready